server:
  port: 8080
spring:
  application:
    name: product-api
  datasource:
    url: jdbc:mysql://mysql:3306/products
    username: ${db.user}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  cache:
    type: hazelcast
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT
  main:
    allow-circular-references: true
springdoc:
  api-docs:
    resolve-schema-properties: true
